// Generated by ObjectFlow builder
// Select an application Object based on its typeID
Object* ObjectList::applicationObject(uint16_t type, uint16_t instance, Object* firstObject) {
  switch (type) {
    case 43000: return new TimeSource(type, instance, firstObject);
    case 43010: return new ValueMap(type, instance, firstObject);
    case 43001: return new AnalogInput(type, instance, firstObject);
    case 43002: return new AnalogOutput(type, instance, firstObject);
    case 43003: return new BinaryInput(type, instance, firstObject);
    case 43004: return new BinaryOutput(type, instance, firstObject);
    case 43008: return new Publisher(type, instance, firstObject);
    default: return new Object(type, instance, firstObject);
  }
};