// Generated by ObjectFlow builder
namespace ObjectFlow
{
  const InstanceTemplate instanceList[] = {
    { 43000, 0, 27005, 0, linkType, (AnyValueType){.linkType = {43001,0} } },
    { 43000, 0, 27006, 0, timeType, (AnyValueType){.timeType = 0 } },
    { 43000, 0, 27007, 0, timeType, (AnyValueType){.timeType = 1000 } },
    { 43000, 0, 27008, 0, timeType, (AnyValueType){.timeType = 0 } },
    { 43000, 0, 27003, 0, timeType, (AnyValueType){.timeType = 0 } },
    { 43001, 0, 27001, 0, integerType, (AnyValueType){.integerType = 0 } },
    { 43001, 0, 27005, 0, linkType, (AnyValueType){.linkType = {43010,0} } },
    { 43001, 0, 27006, 0, timeType, (AnyValueType){.timeType = 0 } },
    { 43001, 0, 27007, 0, timeType, (AnyValueType){.timeType = 0 } },
    { 43001, 0, 27008, 0, timeType, (AnyValueType){.timeType = 0 } },
    { 43001, 0, 27015, 0, integerType, (AnyValueType){.integerType = 7 } },
    { 43010, 0, 27001, 0, floatType, (AnyValueType){.floatType = 0.000000 } },
    { 43010, 0, 27002, 0, integerType, (AnyValueType){.integerType = 0 } },
    { 43010, 0, 27005, 0, linkType, (AnyValueType){.linkType = {43008,0} } },
    { 43010, 0, 27008, 0, floatType, (AnyValueType){.floatType = 0.000000 } },
    { 43010, 0, 27009, 0, floatType, (AnyValueType){.floatType = 0.000000 } },
    { 43010, 0, 27010, 0, floatType, (AnyValueType){.floatType = 0.000000 } },
    { 43010, 0, 27011, 0, floatType, (AnyValueType){.floatType = 0.000000 } },
    { 43010, 0, 27012, 0, floatType, (AnyValueType){.floatType = 0.000000 } },
    { 43010, 0, 27013, 0, floatType, (AnyValueType){.floatType = 100.000000 } },
    { 43010, 0, 27014, 0, stringType, (AnyValueType){.stringType = C } },
    { 43008, 0, 27002, 0, floatType, (AnyValueType){.floatType = 0.000000 } },
  };
}